name: Integration tests and coverage

#
# Unit and integration tests, with coverage report and check and badge for PR on master branch
#

on:
  pull_request:
    branches:
      - master

jobs:
  test-coverage:
    runs-on: ubuntu-latest
#    env:
#      COV_TOT: 60
#      COV_NEW: 75
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Test
        run: mvn verify --batch-mode --fail-at-end

      # publishes data of failed tests
      - name: Publish reports
        # to ensure it proceeds in case of test failures
        if: ${{ always() }}
        uses: ScaCap/action-surefire-report@v1
        with:
          # ignore surefire reports (unit tests)
          report_paths: '**/failsafe-reports/TEST-*.xml'
          # default is false, another action will fail the pipeline if there are test failures
          fail_on_test_failures: false
          # default is true, another action will fail the pipeline if there are no tests
          fail_if_no_tests: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # adds a comment which shows coverage ratio
#      - name: Report coverage
#        id: jacoco
#        uses: Madrapps/jacoco-report@v1.2
#        with:
#          paths: './target/site/jacoco-merged-report/jacoco.xml'
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: env.COV_TOT
#          min-coverage-changed-files: env.COV_NEW

      # fails the action if coverage is not enough
#      - name: Check coverage
#        uses: actions/github-script@v5.0.0
#        with:
#          # doesn't seem to work with 'if:' above
#          script: |
#            const { COV_TOT, COV_NEW } = process.env;
#            const covTot = ${{ steps.jacoco.outputs.coverage-overall }};
#            const covNew = ${{ steps.jacoco.outputs.coverage-changed-files }};
#            const totBool = covTot < COV_TOT;
#            const newBool = covNew < COV_NEW;
#            if (totBool || newBool) {
#              const msg = `Code coverage ratio below required minima.\nOverall: ${covTot} (target ${COV_TOT}).\nChanged files: ${covNew} (target ${COV_NEW})`
#              core.setFailed(msg)
#            }

      # creates coverage badge from jacoco merged report
      - name: Create badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco-merged-report/jacoco.csv
          # original is 100 90 80 70 60 0
          intervals: 80 70 60 50 40 0

      # commits and pushes the badge if it has changed
      - name: Commit and push badge
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Commit updated badge'
          add: '*.svg'
